// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.normandy.startupRolloutPrefs.network.http.http2.websockets", false);
user_pref("app.normandy.startupRolloutPrefs.network.http.spdy.websockets", false);
user_pref("app.normandy.user_id", "813279f0-b4fe-4eb6-a56a-ce9d64222b9d");
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1680285955);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1680285954);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "{7c95ab99-5f39-4cae-a28f-7507c8dcc6a9}");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1680285953);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 136);
user_pref("browser.newtabpage.activity-stream.impressionId", "{62ea5d49-7d7e-4735-9532-85dcc7e55b82}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1680285954);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1680285954718");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1680307554718");
user_pref("browser.search.region", "CA");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1680285954");
user_pref("browser.startup.couldRestoreSession.count", 1);
user_pref("browser.startup.homepage_override.buildID", "20230321162322");
user_pref("browser.startup.homepage_override.mstone", "111.0.1");
user_pref("browser.startup.lastColdStartupCheck", 1680285953);
user_pref("browser.tabs.remote.autostart", false);
user_pref("browser.tabs.remote.autostart.2", false);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"firefox-view-button\",\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\"],\"currentVersion\":19,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 2);
user_pref("browser.urlbar.quicksuggest.scenario", "history");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1680285954203");
user_pref("distribution.canonical-002.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "111.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "CA");
user_pref("doh-rollout.mode", 2);
user_pref("doh-rollout.self-enabled", true);
user_pref("doh-rollout.uri", "https://private.canadianshield.cira.ca/dns-query");
user_pref("dom.disable_open_during_load", false);
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("dom.max_script_run_time", 0);
user_pref("dom.min_background_timeout_value", 10);
user_pref("dom.push.userAgentID", "c24f1e68e4b74cc28ce5cb3f0ededf84");
user_pref("extensions.autoDisableScopes", 0);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.enabledScopes", 15);
user_pref("extensions.getAddons.cache.lastUpdate", 1680285953);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20230321162322");
user_pref("extensions.lastAppVersion", "111.0.1");
user_pref("extensions.lastPlatformVersion", "111.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"8b89e1e3-9b38-4c1d-aea0-893d2062c1e4\",\"pictureinpicture@mozilla.org\":\"7c6f82bc-65b0-4452-8248-fb24a209948b\",\"screenshots@mozilla.org\":\"9659ab77-614e-49d5-89dd-8d86918ea7ca\",\"webcompat-reporter@mozilla.org\":\"ba3081da-1dde-43e6-ae4d-b12edc725ed3\",\"webcompat@mozilla.org\":\"3b35ca9c-054f-4eee-ba8e-15a143a34de0\",\"addons-search-detection@mozilla.com\":\"ab52ebdf-edce-49ba-b893-de9c06f9b0bb\",\"google@search.mozilla.org\":\"2485611e-d123-48f8-86bc-203934cb3308\",\"wikipedia@search.mozilla.org\":\"b76d4d24-ce28-4b4c-8004-d4a4c84099f6\",\"bing@search.mozilla.org\":\"72f5bacd-2792-4603-a42b-437d06e650c7\",\"ddg@search.mozilla.org\":\"af9b47e3-09b7-4ee9-a798-81ad965ebdc9\",\"ebay@search.mozilla.org\":\"2ecdaff7-42f4-433d-9497-2c9f539e0864\",\"qwant@search.mozilla.org\":\"20446219-97f3-4a27-b1da-a017d01986fa\",\"amazon@search.mozilla.org\":\"e1a0fb20-f14b-4d16-a632-c18c2c51a511\",\"default-theme@mozilla.org\":\"62cea769-2b28-457d-bf27-ad99fe20d955\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.sandbox.content.tempDirSuffix", "d9a297f6-0ace-400e-9f87-b2d5cce900f6");
user_pref("services.sync.engine.addresses.available", true);
user_pref("toolkit.telemetry.cachedClientID", "e3771a72-d50c-4cc7-940e-1e025b462a96");
user_pref("toolkit.telemetry.previousBuildID", "20230321162322");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
