// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.normandy.startupRolloutPrefs.network.http.http2.websockets", false);
user_pref("app.normandy.startupRolloutPrefs.network.http.spdy.websockets", false);
user_pref("app.normandy.user_id", "3a6dd541-e70c-47b2-bf30-775299089167");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1680282571);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1680282931);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1680282811);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1680282691);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1680282600);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "{ef7cadf3-aec4-4de2-94b2-d249e32ff57c}");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1680282540);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 136);
user_pref("browser.newtabpage.activity-stream.impressionId", "{7ad4766f-8c66-4e9b-82bf-a611dd87e5fc}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1680282541);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1680282559035");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1680284343035");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1680282542491");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1680304142491");
user_pref("browser.search.region", "CA");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1680282542");
user_pref("browser.startup.couldRestoreSession.count", 1);
user_pref("browser.startup.homepage_override.buildID", "20230321162322");
user_pref("browser.startup.homepage_override.mstone", "111.0.1");
user_pref("browser.startup.lastColdStartupCheck", 1680282541);
user_pref("browser.tabs.remote.autostart", false);
user_pref("browser.tabs.remote.autostart.2", false);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"firefox-view-button\",\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\"],\"currentVersion\":19,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 2);
user_pref("browser.urlbar.quicksuggest.scenario", "history");
user_pref("browser.urlbar.tipShownCount.searchTip_onboard", 1);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1680282542001");
user_pref("distribution.canonical-002.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "111.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "CA");
user_pref("doh-rollout.mode", 2);
user_pref("doh-rollout.self-enabled", true);
user_pref("doh-rollout.uri", "https://private.canadianshield.cira.ca/dns-query");
user_pref("dom.disable_open_during_load", false);
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("dom.max_script_run_time", 0);
user_pref("dom.min_background_timeout_value", 10);
user_pref("dom.push.userAgentID", "9708d8a3d82b449ea5388efdac68bb84");
user_pref("extensions.autoDisableScopes", 0);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.enabledScopes", 15);
user_pref("extensions.getAddons.cache.lastUpdate", 1680282541);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20230321162322");
user_pref("extensions.lastAppVersion", "111.0.1");
user_pref("extensions.lastPlatformVersion", "111.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"8fb65ecf-3e83-4c56-826e-e31c62ed3f79\",\"pictureinpicture@mozilla.org\":\"214f7a3d-599f-43b4-bf1b-b48314f4f1cc\",\"screenshots@mozilla.org\":\"f4b4408f-a73d-4445-8e72-8b0fc6fc06cf\",\"webcompat-reporter@mozilla.org\":\"7134cb81-cd17-4b15-b9c0-c0600b38fb44\",\"webcompat@mozilla.org\":\"60d7ce69-fe64-4b8b-aa15-2f27ad5295ab\",\"addons-search-detection@mozilla.com\":\"7536bb3a-b02e-4e65-b2ab-8af7a5d513f8\",\"google@search.mozilla.org\":\"8ef6e2ba-166e-4111-94c9-a7fd5a7fb366\",\"wikipedia@search.mozilla.org\":\"3f94e8a8-86ca-4dfe-8be5-4866d2f75fe0\",\"bing@search.mozilla.org\":\"31d609f8-b6d6-4056-ac99-9e571dfefd80\",\"ddg@search.mozilla.org\":\"c2f9c6d3-ce1c-4216-a5b8-61042618e877\",\"ebay@search.mozilla.org\":\"d3689eca-f963-41d2-9505-478b1b7ad21e\",\"qwant@search.mozilla.org\":\"df790945-6dcf-4049-99df-2819b560746a\",\"amazon@search.mozilla.org\":\"885e4105-3eed-4fdf-9839-6faa69e2657e\",\"default-theme@mozilla.org\":\"d94ccf8d-2827-4940-9043-a6a4a9f745c7\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.hashValue", "94531e267314de661b2205c606283fb066d781e5c11027578f2a3c3aa353437c2289544074a28101b6b6f0179f0fe6bd890a0ae2bb6e1cf9053650472576366c");
user_pref("media.gmp-gmpopenh264.lastDownload", 1680282589);
user_pref("media.gmp-gmpopenh264.lastInstallStart", 1680282589);
user_pref("media.gmp-gmpopenh264.lastUpdate", 1680282589);
user_pref("media.gmp-gmpopenh264.version", "1.8.1.2");
user_pref("media.gmp-manager.buildID", "20230321162322");
user_pref("media.gmp-manager.lastCheck", 1680282589);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.sandbox.content.tempDirSuffix", "77274bca-8ae4-4a77-ad1b-eb07d21f49e6");
user_pref("services.sync.engine.addresses.available", true);
user_pref("toolkit.startup.last_success", 1680282539);
user_pref("toolkit.telemetry.cachedClientID", "e3771a72-d50c-4cc7-940e-1e025b462a96");
user_pref("toolkit.telemetry.previousBuildID", "20230321162322");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
