// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.normandy.startupRolloutPrefs.network.http.http2.websockets", false);
user_pref("app.normandy.startupRolloutPrefs.network.http.spdy.websockets", false);
user_pref("app.normandy.user_id", "4284e756-3178-4488-b3d2-cecfce037f15");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1682112379);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1682112351);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1682112350);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1682112409);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "{ae2d046f-403f-4542-adcf-237fdb6dfb5f}");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1682112349);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 136);
user_pref("browser.newtabpage.activity-stream.impressionId", "{7f38a3f9-2be1-4262-9a30-46dfeb31a4ee}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1682112350);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1682112396362");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1682114171362");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1682112350637");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1682133950637");
user_pref("browser.search.region", "CA");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1682112350");
user_pref("browser.startup.couldRestoreSession.count", 1);
user_pref("browser.startup.homepage_override.buildID", "20230414190624");
user_pref("browser.startup.homepage_override.mstone", "112.0.1");
user_pref("browser.startup.lastColdStartupCheck", 1682112350);
user_pref("browser.tabs.remote.autostart", false);
user_pref("browser.tabs.remote.autostart.2", false);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"firefox-view-button\",\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\"],\"currentVersion\":19,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 2);
user_pref("browser.urlbar.quicksuggest.scenario", "history");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1682112350530");
user_pref("distribution.canonical-002.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "112.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "CA");
user_pref("doh-rollout.mode", 2);
user_pref("doh-rollout.self-enabled", true);
user_pref("doh-rollout.uri", "https://private.canadianshield.cira.ca/dns-query");
user_pref("dom.disable_open_during_load", false);
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("dom.max_script_run_time", 0);
user_pref("dom.min_background_timeout_value", 10);
user_pref("dom.push.userAgentID", "e5ab0b8478bf448cb565e578143e2f09");
user_pref("extensions.autoDisableScopes", 0);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.enabledScopes", 15);
user_pref("extensions.getAddons.cache.lastUpdate", 1682112349);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20230414190624");
user_pref("extensions.lastAppVersion", "112.0.1");
user_pref("extensions.lastPlatformVersion", "112.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"29b3607c-ea2e-43f0-9857-1041c2b35b2b\",\"pictureinpicture@mozilla.org\":\"3c4e8bed-fe43-4e15-8c99-db1f53277612\",\"screenshots@mozilla.org\":\"ca2d8afb-c010-4ca4-9ca8-daf763ab9729\",\"webcompat-reporter@mozilla.org\":\"5e49ddb3-e2e6-4c6e-85ef-363aa98609ac\",\"webcompat@mozilla.org\":\"7e9278f4-a858-47e9-b689-bb6b568c9d85\",\"addons-search-detection@mozilla.com\":\"59abc9f4-0c1a-491a-bc4e-94ff4e3b9285\",\"google@search.mozilla.org\":\"7fccb55f-7005-4312-b6af-609bef3f961f\",\"wikipedia@search.mozilla.org\":\"82f8a376-050d-4502-b350-ae32a8a6dd3e\",\"bing@search.mozilla.org\":\"c84a16c7-b02d-42be-b198-dddf1683d129\",\"ddg@search.mozilla.org\":\"f3fcedba-94a1-439e-8d4a-a2e712bcf094\",\"ebay@search.mozilla.org\":\"c5762b49-8969-4eed-a78a-32bada803772\",\"qwant@search.mozilla.org\":\"bd7c8e23-9836-470d-a387-dfb7f440c7c0\",\"amazon@search.mozilla.org\":\"74b9d5dd-7916-4ef8-992d-a045e42022cb\",\"default-theme@mozilla.org\":\"ad59a01e-d57f-4d5e-bdca-10d185533987\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.hashValue", "94531e267314de661b2205c606283fb066d781e5c11027578f2a3c3aa353437c2289544074a28101b6b6f0179f0fe6bd890a0ae2bb6e1cf9053650472576366c");
user_pref("media.gmp-gmpopenh264.lastDownload", 1682112387);
user_pref("media.gmp-gmpopenh264.lastInstallStart", 1682112387);
user_pref("media.gmp-gmpopenh264.lastUpdate", 1682112387);
user_pref("media.gmp-gmpopenh264.version", "1.8.1.2");
user_pref("media.gmp-manager.buildID", "20230414190624");
user_pref("media.gmp-manager.lastCheck", 1682112387);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.sandbox.content.tempDirSuffix", "5fb3920c-198a-4c28-94d2-19e14780f650");
user_pref("services.sync.engine.addresses.available", true);
user_pref("toolkit.startup.last_success", 1682112348);
user_pref("toolkit.telemetry.cachedClientID", "e3771a72-d50c-4cc7-940e-1e025b462a96");
user_pref("toolkit.telemetry.previousBuildID", "20230414190624");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
